# Generated by Django 3.0.4 on 2020-09-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adultos', models.IntegerField()),
                ('niños', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('paisOrigen', models.CharField(choices=[('Alemania', 'Alemania'), ('Canadá', 'Canadá'), ('Mexico', 'Mexico'), ('Colombia', 'Colombia'), ('Argentina', 'Argentina'), ('Brasil', 'Brasil'), ('Peru', 'Peru'), ('Ecuador', 'Ecuador'), ('Costa Rica', 'Costa Rica'), ('Estado Unidos', 'Estado Unidos'), ('España', 'España')], max_length=30)),
                ('fechaNacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
            },
        ),
    ]
